packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@clerk/shared': true
  '@sentry/cli': false
  '@swc/core': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  sharp: true
  utf-8-validate: true
catalog:
  "@types/node": ^20.19.25
  convex: ^1.39.1
  dotenv: ^17.2.3
  typescript: ^5
  zod: ^4.1.13
