import prisma from "@agenci/db";
import { appendThreadMessage, listThreadMessages, recordTeamReply } from "@/modules/conversations/service";
const [THREAD, SESSION] = process.argv.slice(2);
const AGENT = "cmuh7brf10006l90xgqxqaj1f";
const ORG = "A1WE1UeLYwDWBsVHHd4ZlReTrNZrCc3Q";
await appendThreadMessage({ threadId: THREAD!, resourceId: `${ORG}:contact:${SESSION}`, role: "assistant", text: "Hei! Dette er Abdifatah fra Royalrevue. Hva kan jeg hjelpe deg med?", metadata: { author: "team", authorName: "Abdifatah Hassan" } });
await recordTeamReply(THREAD!, "Hei! Dette er Abdifatah fra Royalrevue. Hva kan jeg hjelpe deg med?");
const msgs = await listThreadMessages(THREAD!);
console.log("7. team svarer →", msgs.map((m) => m.author).join(" → "));
const visitor = async (path: string, input: unknown) => (await (await fetch(`http://localhost:3003/rpc/${path}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Contact-Session-Id": SESSION! }, body: JSON.stringify({ json: input }) })).json() as any).json;
const h = await visitor("public/chat/history", { threadId: THREAD });
const last = h.messages.at(-1);
console.log(`8. widgeten henter [${h.status}]: ${last.author} (${last.authorName}): ${last.text}`);
await prisma.conversation.update({ where: { id: THREAD! }, data: { status: "unresolved" } });
console.log("9. gitt tilbake til agenten");
const t = Date.now();
const back = await visitor("public/chat/send", { agentId: AGENT, threadId: THREAD, message: "Takk! Hvem svarte meg nettopp, og har dere gratis frakt?" });
console.log(`10. agenten svarer igjen (${((Date.now() - t) / 1000).toFixed(1)}s) [${back.status}]: ${back.message}`);
const row = await prisma.conversation.findUnique({ where: { id: THREAD! }, select: { status: true, messageCount: true, lastMessageRole: true } });
console.log("11. innboks-raden:", JSON.stringify(row));
process.exit(0);
