/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOrgOrgSlugRouteRouteImport } from './routes/_authed/org/$orgSlug/route'
import { Route as AuthedOrgCreateRouteImport } from './routes/_authed/org/create'
import { Route as AuthedOrgOrganizationRouteImport } from './routes/_authed/org/organization'
import { Route as AuthedOrgOrgSlugIndexRouteImport } from './routes/_authed/org/$orgSlug/index'
import { Route as AuthedOrgOrgSlugAgentsRouteImport } from './routes/_authed/org/$orgSlug/agents'
import { Route as AuthedOrgOrgSlugAgentsIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/route'
import { Route as AuthedOrgOrgSlugAgentsCreateRouteImport } from './routes/_authed/org/$orgSlug/agents/create'
import { Route as AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/$'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations'
import { Route as AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/customization'
import { Route as AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/files'
import { Route as AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/integrations'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugRouteRoute = AuthedOrgOrgSlugRouteRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgCreateRoute = AuthedOrgCreateRouteImport.update({
  id: '/org/create',
  path: '/org/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrganizationRoute = AuthedOrgOrganizationRouteImport.update({
  id: '/org/organization',
  path: '/org/organization',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugIndexRoute = AuthedOrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugAgentsRoute = AuthedOrgOrgSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugAgentsIndexRoute =
  AuthedOrgOrgSlugAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdRouteRoute =
  AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsCreateRoute =
  AuthedOrgOrgSlugAgentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdIndexRoute =
  AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdSplatRoute =
  AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute =
  AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdFilesRoute =
  AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute =
  AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdConversationsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/organization': typeof AuthedOrgOrganizationRoute
  '/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  '/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
  '/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  '/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/org/$orgSlug/agents/': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  '/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/org/$orgSlug/agents/$agentId/': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/org/$orgSlug/agents/$agentId/conversations/': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/organization': typeof AuthedOrgOrganizationRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugIndexRoute
  '/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/_authed/org/create': typeof AuthedOrgCreateRoute
  '/_authed/org/organization': typeof AuthedOrgOrganizationRoute
  '/_authed/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  '/_authed/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  '/_authed/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/_authed/org/$orgSlug/agents/': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  '/_authed/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/_authed/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/_authed/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/_authed/org/$orgSlug/agents/$agentId/': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations/': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/org/$orgSlug'
    | '/org/create'
    | '/org/organization'
    | '/org/$orgSlug/agents'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/agents/$agentId'
    | '/org/$orgSlug/agents/create'
    | '/org/$orgSlug/agents/'
    | '/org/$orgSlug/agents/$agentId/$'
    | '/org/$orgSlug/agents/$agentId/conversations'
    | '/org/$orgSlug/agents/$agentId/customization'
    | '/org/$orgSlug/agents/$agentId/files'
    | '/org/$orgSlug/agents/$agentId/integrations'
    | '/org/$orgSlug/agents/$agentId/'
    | '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/org/$orgSlug/agents/$agentId/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/org/create'
    | '/org/organization'
    | '/org/$orgSlug'
    | '/org/$orgSlug/agents/create'
    | '/org/$orgSlug/agents'
    | '/org/$orgSlug/agents/$agentId/$'
    | '/org/$orgSlug/agents/$agentId/customization'
    | '/org/$orgSlug/agents/$agentId/files'
    | '/org/$orgSlug/agents/$agentId/integrations'
    | '/org/$orgSlug/agents/$agentId'
    | '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/org/$orgSlug/agents/$agentId/conversations'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/org/$orgSlug'
    | '/_authed/org/create'
    | '/_authed/org/organization'
    | '/_authed/org/$orgSlug/agents'
    | '/_authed/org/$orgSlug/'
    | '/_authed/org/$orgSlug/agents/$agentId'
    | '/_authed/org/$orgSlug/agents/create'
    | '/_authed/org/$orgSlug/agents/'
    | '/_authed/org/$orgSlug/agents/$agentId/$'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations'
    | '/_authed/org/$orgSlug/agents/$agentId/customization'
    | '/_authed/org/$orgSlug/agents/$agentId/files'
    | '/_authed/org/$orgSlug/agents/$agentId/integrations'
    | '/_authed/org/$orgSlug/agents/$agentId/'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug': {
      id: '/_authed/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AuthedOrgOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/create': {
      id: '/_authed/org/create'
      path: '/org/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof AuthedOrgCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/organization': {
      id: '/_authed/org/organization'
      path: '/org/organization'
      fullPath: '/org/organization'
      preLoaderRoute: typeof AuthedOrgOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug/': {
      id: '/_authed/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/agents': {
      id: '/_authed/org/$orgSlug/agents'
      path: '/agents'
      fullPath: '/org/$orgSlug/agents'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/agents/': {
      id: '/_authed/org/$orgSlug/agents/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId': {
      id: '/_authed/org/$orgSlug/agents/$agentId'
      path: '/$agentId'
      fullPath: '/org/$orgSlug/agents/$agentId'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/agents/create': {
      id: '/_authed/org/$orgSlug/agents/create'
      path: '/create'
      fullPath: '/org/$orgSlug/agents/create'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsCreateRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/': {
      id: '/_authed/org/$orgSlug/agents/$agentId/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/$agentId/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/$': {
      id: '/_authed/org/$orgSlug/agents/$agentId/$'
      path: '/$'
      fullPath: '/org/$orgSlug/agents/$agentId/$'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations'
      path: '/conversations'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/customization': {
      id: '/_authed/org/$orgSlug/agents/$agentId/customization'
      path: '/customization'
      fullPath: '/org/$orgSlug/agents/$agentId/customization'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/files': {
      id: '/_authed/org/$orgSlug/agents/$agentId/files'
      path: '/files'
      fullPath: '/org/$orgSlug/agents/$agentId/files'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/integrations': {
      id: '/_authed/org/$orgSlug/agents/$agentId/integrations'
      path: '/integrations'
      fullPath: '/org/$orgSlug/agents/$agentId/integrations'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations/': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRoute
    }
  }
}

interface AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
}

const AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren: AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute,
    AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute,
  }

const AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren =
  AuthedOrgOrgSlugAgentsAgentIdConversationsRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren,
  )

interface AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdSplatRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  AuthedOrgOrgSlugAgentsAgentIdConversationsRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute: typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  AuthedOrgOrgSlugAgentsAgentIdFilesRoute: typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  AuthedOrgOrgSlugAgentsAgentIdIndexRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
}

const AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren: AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdSplatRoute:
      AuthedOrgOrgSlugAgentsAgentIdSplatRoute,
    AuthedOrgOrgSlugAgentsAgentIdConversationsRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren,
    AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute:
      AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute,
    AuthedOrgOrgSlugAgentsAgentIdFilesRoute:
      AuthedOrgOrgSlugAgentsAgentIdFilesRoute,
    AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute:
      AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute,
    AuthedOrgOrgSlugAgentsAgentIdIndexRoute:
      AuthedOrgOrgSlugAgentsAgentIdIndexRoute,
  }

const AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren =
  AuthedOrgOrgSlugAgentsAgentIdRouteRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren,
  )

interface AuthedOrgOrgSlugAgentsRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdRouteRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  AuthedOrgOrgSlugAgentsCreateRoute: typeof AuthedOrgOrgSlugAgentsCreateRoute
  AuthedOrgOrgSlugAgentsIndexRoute: typeof AuthedOrgOrgSlugAgentsIndexRoute
}

const AuthedOrgOrgSlugAgentsRouteChildren: AuthedOrgOrgSlugAgentsRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdRouteRoute:
      AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren,
    AuthedOrgOrgSlugAgentsCreateRoute: AuthedOrgOrgSlugAgentsCreateRoute,
    AuthedOrgOrgSlugAgentsIndexRoute: AuthedOrgOrgSlugAgentsIndexRoute,
  }

const AuthedOrgOrgSlugAgentsRouteWithChildren =
  AuthedOrgOrgSlugAgentsRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsRouteChildren,
  )

interface AuthedOrgOrgSlugRouteRouteChildren {
  AuthedOrgOrgSlugAgentsRoute: typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  AuthedOrgOrgSlugIndexRoute: typeof AuthedOrgOrgSlugIndexRoute
}

const AuthedOrgOrgSlugRouteRouteChildren: AuthedOrgOrgSlugRouteRouteChildren = {
  AuthedOrgOrgSlugAgentsRoute: AuthedOrgOrgSlugAgentsRouteWithChildren,
  AuthedOrgOrgSlugIndexRoute: AuthedOrgOrgSlugIndexRoute,
}

const AuthedOrgOrgSlugRouteRouteWithChildren =
  AuthedOrgOrgSlugRouteRoute._addFileChildren(
    AuthedOrgOrgSlugRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgOrgSlugRouteRoute: typeof AuthedOrgOrgSlugRouteRouteWithChildren
  AuthedOrgCreateRoute: typeof AuthedOrgCreateRoute
  AuthedOrgOrganizationRoute: typeof AuthedOrgOrganizationRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgOrgSlugRouteRoute: AuthedOrgOrgSlugRouteRouteWithChildren,
  AuthedOrgCreateRoute: AuthedOrgCreateRoute,
  AuthedOrgOrganizationRoute: AuthedOrgOrganizationRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
