/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GlemtPassordRouteImport } from './routes/glemt-passord'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NyttPassordRouteImport } from './routes/nytt-passord'
import { Route as ToTrinnRouteImport } from './routes/to-trinn'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBetalingRouteImport } from './routes/_authed/betaling'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthedFakturaInvoiceIdRouteImport } from './routes/_authed/faktura.$invoiceId'
import { Route as AuthedOrgOrgSlugRouteRouteImport } from './routes/_authed/org/$orgSlug/route'
import { Route as AuthedOrgCreateRouteImport } from './routes/_authed/org/create'
import { Route as AuthedOrgOrganizationRouteImport } from './routes/_authed/org/organization'
import { Route as AuthedOrgOrgSlugIndexRouteImport } from './routes/_authed/org/$orgSlug/index'
import { Route as AuthedOrgOrgSlugAgentsRouteImport } from './routes/_authed/org/$orgSlug/agents'
import { Route as AuthedOrgOrgSlugBillingRouteImport } from './routes/_authed/org/$orgSlug/billing'
import { Route as AuthedOrgOrgSlugMembersRouteImport } from './routes/_authed/org/$orgSlug/members'
import { Route as AuthedOrgOrgSlugOnboardingRouteImport } from './routes/_authed/org/$orgSlug/onboarding'
import { Route as AuthedOrgOrgSlugAgentsIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/route'
import { Route as AuthedOrgOrgSlugAgentsCreateRouteImport } from './routes/_authed/org/$orgSlug/agents/create'
import { Route as AuthedOrgOrgSlugSettingsIndexRouteImport } from './routes/_authed/org/$orgSlug/settings/index'
import { Route as AuthedOrgOrgSlugSettingsSectionRouteImport } from './routes/_authed/org/$orgSlug/settings/$section'
import { Route as AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/$'
import { Route as AuthedOrgOrgSlugAgentsAgentIdBillingRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/billing'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations'
import { Route as AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/customization'
import { Route as AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/files'
import { Route as AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/integrations'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'
import { Route as AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/settings/index'
import { Route as AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRouteImport } from './routes/_authed/org/$orgSlug/agents/$agentId/settings/$section'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GlemtPassordRoute = GlemtPassordRouteImport.update({
  id: '/glemt-passord',
  path: '/glemt-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NyttPassordRoute = NyttPassordRouteImport.update({
  id: '/nytt-passord',
  path: '/nytt-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const ToTrinnRoute = ToTrinnRouteImport.update({
  id: '/to-trinn',
  path: '/to-trinn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBetalingRoute = AuthedBetalingRouteImport.update({
  id: '/betaling',
  path: '/betaling',
  getParentRoute: () => AuthedRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedFakturaInvoiceIdRoute = AuthedFakturaInvoiceIdRouteImport.update({
  id: '/faktura/$invoiceId',
  path: '/faktura/$invoiceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugRouteRoute = AuthedOrgOrgSlugRouteRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgCreateRoute = AuthedOrgCreateRouteImport.update({
  id: '/org/create',
  path: '/org/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrganizationRoute = AuthedOrgOrganizationRouteImport.update({
  id: '/org/organization',
  path: '/org/organization',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugIndexRoute = AuthedOrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugAgentsRoute = AuthedOrgOrgSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugBillingRoute = AuthedOrgOrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugMembersRoute = AuthedOrgOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugOnboardingRoute =
  AuthedOrgOrgSlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsIndexRoute =
  AuthedOrgOrgSlugAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdRouteRoute =
  AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsCreateRoute =
  AuthedOrgOrgSlugAgentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedOrgOrgSlugAgentsRoute,
  } as any)
const AuthedOrgOrgSlugSettingsIndexRoute =
  AuthedOrgOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
  } as any)
const AuthedOrgOrgSlugSettingsSectionRoute =
  AuthedOrgOrgSlugSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdIndexRoute =
  AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdSplatRoute =
  AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdBillingRoute =
  AuthedOrgOrgSlugAgentsAgentIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute =
  AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdFilesRoute =
  AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute =
  AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdConversationsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute =
  AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdConversationsRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute =
  AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)
const AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute =
  AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AuthedOrgOrgSlugAgentsAgentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/nytt-passord': typeof NyttPassordRoute
  '/to-trinn': typeof ToTrinnRoute
  '/admin': typeof AuthedAdminRoute
  '/betaling': typeof AuthedBetalingRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/faktura/$invoiceId': typeof AuthedFakturaInvoiceIdRoute
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/organization': typeof AuthedOrgOrganizationRoute
  '/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  '/org/$orgSlug/billing': typeof AuthedOrgOrgSlugBillingRoute
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug/onboarding': typeof AuthedOrgOrgSlugOnboardingRoute
  '/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
  '/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  '/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/org/$orgSlug/settings/$section': typeof AuthedOrgOrgSlugSettingsSectionRoute
  '/org/$orgSlug/agents/': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/org/$orgSlug/settings/': typeof AuthedOrgOrgSlugSettingsIndexRoute
  '/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/org/$orgSlug/agents/$agentId/billing': typeof AuthedOrgOrgSlugAgentsAgentIdBillingRoute
  '/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  '/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/org/$orgSlug/agents/$agentId/': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/org/$orgSlug/agents/$agentId/settings/$section': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute
  '/org/$orgSlug/agents/$agentId/conversations/': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
  '/org/$orgSlug/agents/$agentId/settings/': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/nytt-passord': typeof NyttPassordRoute
  '/to-trinn': typeof ToTrinnRoute
  '/admin': typeof AuthedAdminRoute
  '/betaling': typeof AuthedBetalingRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/': typeof AuthedIndexRoute
  '/faktura/$invoiceId': typeof AuthedFakturaInvoiceIdRoute
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/organization': typeof AuthedOrgOrganizationRoute
  '/org/$orgSlug/billing': typeof AuthedOrgOrgSlugBillingRoute
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug/onboarding': typeof AuthedOrgOrgSlugOnboardingRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugIndexRoute
  '/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/org/$orgSlug/settings/$section': typeof AuthedOrgOrgSlugSettingsSectionRoute
  '/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/org/$orgSlug/settings': typeof AuthedOrgOrgSlugSettingsIndexRoute
  '/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/org/$orgSlug/agents/$agentId/billing': typeof AuthedOrgOrgSlugAgentsAgentIdBillingRoute
  '/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/org/$orgSlug/agents/$agentId/settings/$section': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute
  '/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
  '/org/$orgSlug/agents/$agentId/settings': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/glemt-passord': typeof GlemtPassordRoute
  '/login': typeof LoginRoute
  '/nytt-passord': typeof NyttPassordRoute
  '/to-trinn': typeof ToTrinnRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/betaling': typeof AuthedBetalingRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/_authed/faktura/$invoiceId': typeof AuthedFakturaInvoiceIdRoute
  '/_authed/org/create': typeof AuthedOrgCreateRoute
  '/_authed/org/organization': typeof AuthedOrgOrganizationRoute
  '/_authed/org/$orgSlug/agents': typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  '/_authed/org/$orgSlug/billing': typeof AuthedOrgOrgSlugBillingRoute
  '/_authed/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/_authed/org/$orgSlug/onboarding': typeof AuthedOrgOrgSlugOnboardingRoute
  '/_authed/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId': typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  '/_authed/org/$orgSlug/agents/create': typeof AuthedOrgOrgSlugAgentsCreateRoute
  '/_authed/org/$orgSlug/settings/$section': typeof AuthedOrgOrgSlugSettingsSectionRoute
  '/_authed/org/$orgSlug/agents/': typeof AuthedOrgOrgSlugAgentsIndexRoute
  '/_authed/org/$orgSlug/settings/': typeof AuthedOrgOrgSlugSettingsIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId/$': typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  '/_authed/org/$orgSlug/agents/$agentId/billing': typeof AuthedOrgOrgSlugAgentsAgentIdBillingRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  '/_authed/org/$orgSlug/agents/$agentId/customization': typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  '/_authed/org/$orgSlug/agents/$agentId/files': typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  '/_authed/org/$orgSlug/agents/$agentId/integrations': typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  '/_authed/org/$orgSlug/agents/$agentId/': typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  '/_authed/org/$orgSlug/agents/$agentId/settings/$section': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute
  '/_authed/org/$orgSlug/agents/$agentId/conversations/': typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
  '/_authed/org/$orgSlug/agents/$agentId/settings/': typeof AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glemt-passord'
    | '/login'
    | '/nytt-passord'
    | '/to-trinn'
    | '/admin'
    | '/betaling'
    | '/accept-invitation/$invitationId'
    | '/org/$orgSlug'
    | '/faktura/$invoiceId'
    | '/org/create'
    | '/org/organization'
    | '/org/$orgSlug/agents'
    | '/org/$orgSlug/billing'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/onboarding'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/agents/$agentId'
    | '/org/$orgSlug/agents/create'
    | '/org/$orgSlug/settings/$section'
    | '/org/$orgSlug/agents/'
    | '/org/$orgSlug/settings/'
    | '/org/$orgSlug/agents/$agentId/$'
    | '/org/$orgSlug/agents/$agentId/billing'
    | '/org/$orgSlug/agents/$agentId/conversations'
    | '/org/$orgSlug/agents/$agentId/customization'
    | '/org/$orgSlug/agents/$agentId/files'
    | '/org/$orgSlug/agents/$agentId/integrations'
    | '/org/$orgSlug/agents/$agentId/'
    | '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/org/$orgSlug/agents/$agentId/settings/$section'
    | '/org/$orgSlug/agents/$agentId/conversations/'
    | '/org/$orgSlug/agents/$agentId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/glemt-passord'
    | '/login'
    | '/nytt-passord'
    | '/to-trinn'
    | '/admin'
    | '/betaling'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/faktura/$invoiceId'
    | '/org/create'
    | '/org/organization'
    | '/org/$orgSlug/billing'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/onboarding'
    | '/org/$orgSlug'
    | '/org/$orgSlug/agents/create'
    | '/org/$orgSlug/settings/$section'
    | '/org/$orgSlug/agents'
    | '/org/$orgSlug/settings'
    | '/org/$orgSlug/agents/$agentId/$'
    | '/org/$orgSlug/agents/$agentId/billing'
    | '/org/$orgSlug/agents/$agentId/customization'
    | '/org/$orgSlug/agents/$agentId/files'
    | '/org/$orgSlug/agents/$agentId/integrations'
    | '/org/$orgSlug/agents/$agentId'
    | '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/org/$orgSlug/agents/$agentId/settings/$section'
    | '/org/$orgSlug/agents/$agentId/conversations'
    | '/org/$orgSlug/agents/$agentId/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/glemt-passord'
    | '/login'
    | '/nytt-passord'
    | '/to-trinn'
    | '/_authed/admin'
    | '/_authed/betaling'
    | '/accept-invitation/$invitationId'
    | '/_authed/'
    | '/_authed/org/$orgSlug'
    | '/_authed/faktura/$invoiceId'
    | '/_authed/org/create'
    | '/_authed/org/organization'
    | '/_authed/org/$orgSlug/agents'
    | '/_authed/org/$orgSlug/billing'
    | '/_authed/org/$orgSlug/members'
    | '/_authed/org/$orgSlug/onboarding'
    | '/_authed/org/$orgSlug/'
    | '/_authed/org/$orgSlug/agents/$agentId'
    | '/_authed/org/$orgSlug/agents/create'
    | '/_authed/org/$orgSlug/settings/$section'
    | '/_authed/org/$orgSlug/agents/'
    | '/_authed/org/$orgSlug/settings/'
    | '/_authed/org/$orgSlug/agents/$agentId/$'
    | '/_authed/org/$orgSlug/agents/$agentId/billing'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations'
    | '/_authed/org/$orgSlug/agents/$agentId/customization'
    | '/_authed/org/$orgSlug/agents/$agentId/files'
    | '/_authed/org/$orgSlug/agents/$agentId/integrations'
    | '/_authed/org/$orgSlug/agents/$agentId/'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'
    | '/_authed/org/$orgSlug/agents/$agentId/settings/$section'
    | '/_authed/org/$orgSlug/agents/$agentId/conversations/'
    | '/_authed/org/$orgSlug/agents/$agentId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GlemtPassordRoute: typeof GlemtPassordRoute
  LoginRoute: typeof LoginRoute
  NyttPassordRoute: typeof NyttPassordRoute
  ToTrinnRoute: typeof ToTrinnRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glemt-passord': {
      id: '/glemt-passord'
      path: '/glemt-passord'
      fullPath: '/glemt-passord'
      preLoaderRoute: typeof GlemtPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nytt-passord': {
      id: '/nytt-passord'
      path: '/nytt-passord'
      fullPath: '/nytt-passord'
      preLoaderRoute: typeof NyttPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-trinn': {
      id: '/to-trinn'
      path: '/to-trinn'
      fullPath: '/to-trinn'
      preLoaderRoute: typeof ToTrinnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/betaling': {
      id: '/_authed/betaling'
      path: '/betaling'
      fullPath: '/betaling'
      preLoaderRoute: typeof AuthedBetalingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/faktura/$invoiceId': {
      id: '/_authed/faktura/$invoiceId'
      path: '/faktura/$invoiceId'
      fullPath: '/faktura/$invoiceId'
      preLoaderRoute: typeof AuthedFakturaInvoiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug': {
      id: '/_authed/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AuthedOrgOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/create': {
      id: '/_authed/org/create'
      path: '/org/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof AuthedOrgCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/organization': {
      id: '/_authed/org/organization'
      path: '/org/organization'
      fullPath: '/org/organization'
      preLoaderRoute: typeof AuthedOrgOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug/': {
      id: '/_authed/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/agents': {
      id: '/_authed/org/$orgSlug/agents'
      path: '/agents'
      fullPath: '/org/$orgSlug/agents'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/billing': {
      id: '/_authed/org/$orgSlug/billing'
      path: '/billing'
      fullPath: '/org/$orgSlug/billing'
      preLoaderRoute: typeof AuthedOrgOrgSlugBillingRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/members': {
      id: '/_authed/org/$orgSlug/members'
      path: '/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof AuthedOrgOrgSlugMembersRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/onboarding': {
      id: '/_authed/org/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/org/$orgSlug/onboarding'
      preLoaderRoute: typeof AuthedOrgOrgSlugOnboardingRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/agents/': {
      id: '/_authed/org/$orgSlug/agents/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId': {
      id: '/_authed/org/$orgSlug/agents/$agentId'
      path: '/$agentId'
      fullPath: '/org/$orgSlug/agents/$agentId'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/agents/create': {
      id: '/_authed/org/$orgSlug/agents/create'
      path: '/create'
      fullPath: '/org/$orgSlug/agents/create'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsCreateRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsRoute
    }
    '/_authed/org/$orgSlug/settings/': {
      id: '/_authed/org/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/org/$orgSlug/settings/'
      preLoaderRoute: typeof AuthedOrgOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/settings/$section': {
      id: '/_authed/org/$orgSlug/settings/$section'
      path: '/settings/$section'
      fullPath: '/org/$orgSlug/settings/$section'
      preLoaderRoute: typeof AuthedOrgOrgSlugSettingsSectionRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/': {
      id: '/_authed/org/$orgSlug/agents/$agentId/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/$agentId/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/$': {
      id: '/_authed/org/$orgSlug/agents/$agentId/$'
      path: '/$'
      fullPath: '/org/$orgSlug/agents/$agentId/$'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSplatRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/billing': {
      id: '/_authed/org/$orgSlug/agents/$agentId/billing'
      path: '/billing'
      fullPath: '/org/$orgSlug/agents/$agentId/billing'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdBillingRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations'
      path: '/conversations'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/customization': {
      id: '/_authed/org/$orgSlug/agents/$agentId/customization'
      path: '/customization'
      fullPath: '/org/$orgSlug/agents/$agentId/customization'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/files': {
      id: '/_authed/org/$orgSlug/agents/$agentId/files'
      path: '/files'
      fullPath: '/org/$orgSlug/agents/$agentId/files'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdFilesRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/integrations': {
      id: '/_authed/org/$orgSlug/agents/$agentId/integrations'
      path: '/integrations'
      fullPath: '/org/$orgSlug/agents/$agentId/integrations'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations/': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations/'
      path: '/'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId': {
      id: '/_authed/org/$orgSlug/agents/$agentId/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/org/$orgSlug/agents/$agentId/conversations/$conversationId'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/settings/': {
      id: '/_authed/org/$orgSlug/agents/$agentId/settings/'
      path: '/settings'
      fullPath: '/org/$orgSlug/agents/$agentId/settings/'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
    '/_authed/org/$orgSlug/agents/$agentId/settings/$section': {
      id: '/_authed/org/$orgSlug/agents/$agentId/settings/$section'
      path: '/settings/$section'
      fullPath: '/org/$orgSlug/agents/$agentId/settings/$section'
      preLoaderRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRouteImport
      parentRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRoute
    }
  }
}

interface AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute
  AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute
}

const AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren: AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsConversationIdRoute,
    AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsIndexRoute,
  }

const AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren =
  AuthedOrgOrgSlugAgentsAgentIdConversationsRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsAgentIdConversationsRouteChildren,
  )

interface AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdSplatRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSplatRoute
  AuthedOrgOrgSlugAgentsAgentIdBillingRoute: typeof AuthedOrgOrgSlugAgentsAgentIdBillingRoute
  AuthedOrgOrgSlugAgentsAgentIdConversationsRoute: typeof AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren
  AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute: typeof AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute
  AuthedOrgOrgSlugAgentsAgentIdFilesRoute: typeof AuthedOrgOrgSlugAgentsAgentIdFilesRoute
  AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute
  AuthedOrgOrgSlugAgentsAgentIdIndexRoute: typeof AuthedOrgOrgSlugAgentsAgentIdIndexRoute
  AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute
  AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute: typeof AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute
}

const AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren: AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdSplatRoute:
      AuthedOrgOrgSlugAgentsAgentIdSplatRoute,
    AuthedOrgOrgSlugAgentsAgentIdBillingRoute:
      AuthedOrgOrgSlugAgentsAgentIdBillingRoute,
    AuthedOrgOrgSlugAgentsAgentIdConversationsRoute:
      AuthedOrgOrgSlugAgentsAgentIdConversationsRouteWithChildren,
    AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute:
      AuthedOrgOrgSlugAgentsAgentIdCustomizationRoute,
    AuthedOrgOrgSlugAgentsAgentIdFilesRoute:
      AuthedOrgOrgSlugAgentsAgentIdFilesRoute,
    AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute:
      AuthedOrgOrgSlugAgentsAgentIdIntegrationsRoute,
    AuthedOrgOrgSlugAgentsAgentIdIndexRoute:
      AuthedOrgOrgSlugAgentsAgentIdIndexRoute,
    AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute:
      AuthedOrgOrgSlugAgentsAgentIdSettingsSectionRoute,
    AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute:
      AuthedOrgOrgSlugAgentsAgentIdSettingsIndexRoute,
  }

const AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren =
  AuthedOrgOrgSlugAgentsAgentIdRouteRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsAgentIdRouteRouteChildren,
  )

interface AuthedOrgOrgSlugAgentsRouteChildren {
  AuthedOrgOrgSlugAgentsAgentIdRouteRoute: typeof AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren
  AuthedOrgOrgSlugAgentsCreateRoute: typeof AuthedOrgOrgSlugAgentsCreateRoute
  AuthedOrgOrgSlugAgentsIndexRoute: typeof AuthedOrgOrgSlugAgentsIndexRoute
}

const AuthedOrgOrgSlugAgentsRouteChildren: AuthedOrgOrgSlugAgentsRouteChildren =
  {
    AuthedOrgOrgSlugAgentsAgentIdRouteRoute:
      AuthedOrgOrgSlugAgentsAgentIdRouteRouteWithChildren,
    AuthedOrgOrgSlugAgentsCreateRoute: AuthedOrgOrgSlugAgentsCreateRoute,
    AuthedOrgOrgSlugAgentsIndexRoute: AuthedOrgOrgSlugAgentsIndexRoute,
  }

const AuthedOrgOrgSlugAgentsRouteWithChildren =
  AuthedOrgOrgSlugAgentsRoute._addFileChildren(
    AuthedOrgOrgSlugAgentsRouteChildren,
  )

interface AuthedOrgOrgSlugRouteRouteChildren {
  AuthedOrgOrgSlugAgentsRoute: typeof AuthedOrgOrgSlugAgentsRouteWithChildren
  AuthedOrgOrgSlugBillingRoute: typeof AuthedOrgOrgSlugBillingRoute
  AuthedOrgOrgSlugMembersRoute: typeof AuthedOrgOrgSlugMembersRoute
  AuthedOrgOrgSlugOnboardingRoute: typeof AuthedOrgOrgSlugOnboardingRoute
  AuthedOrgOrgSlugIndexRoute: typeof AuthedOrgOrgSlugIndexRoute
  AuthedOrgOrgSlugSettingsSectionRoute: typeof AuthedOrgOrgSlugSettingsSectionRoute
  AuthedOrgOrgSlugSettingsIndexRoute: typeof AuthedOrgOrgSlugSettingsIndexRoute
}

const AuthedOrgOrgSlugRouteRouteChildren: AuthedOrgOrgSlugRouteRouteChildren = {
  AuthedOrgOrgSlugAgentsRoute: AuthedOrgOrgSlugAgentsRouteWithChildren,
  AuthedOrgOrgSlugBillingRoute: AuthedOrgOrgSlugBillingRoute,
  AuthedOrgOrgSlugMembersRoute: AuthedOrgOrgSlugMembersRoute,
  AuthedOrgOrgSlugOnboardingRoute: AuthedOrgOrgSlugOnboardingRoute,
  AuthedOrgOrgSlugIndexRoute: AuthedOrgOrgSlugIndexRoute,
  AuthedOrgOrgSlugSettingsSectionRoute: AuthedOrgOrgSlugSettingsSectionRoute,
  AuthedOrgOrgSlugSettingsIndexRoute: AuthedOrgOrgSlugSettingsIndexRoute,
}

const AuthedOrgOrgSlugRouteRouteWithChildren =
  AuthedOrgOrgSlugRouteRoute._addFileChildren(
    AuthedOrgOrgSlugRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedBetalingRoute: typeof AuthedBetalingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgOrgSlugRouteRoute: typeof AuthedOrgOrgSlugRouteRouteWithChildren
  AuthedFakturaInvoiceIdRoute: typeof AuthedFakturaInvoiceIdRoute
  AuthedOrgCreateRoute: typeof AuthedOrgCreateRoute
  AuthedOrgOrganizationRoute: typeof AuthedOrgOrganizationRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedBetalingRoute: AuthedBetalingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgOrgSlugRouteRoute: AuthedOrgOrgSlugRouteRouteWithChildren,
  AuthedFakturaInvoiceIdRoute: AuthedFakturaInvoiceIdRoute,
  AuthedOrgCreateRoute: AuthedOrgCreateRoute,
  AuthedOrgOrganizationRoute: AuthedOrgOrganizationRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GlemtPassordRoute: GlemtPassordRoute,
  LoginRoute: LoginRoute,
  NyttPassordRoute: NyttPassordRoute,
  ToTrinnRoute: ToTrinnRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
