import { Composition } from "remotion";
import { CityConversation } from "../modules/landing/remotion/scenes/city";
import { CallConversation } from "../modules/landing/remotion/scenes/call";
import { LaptopConversation } from "../modules/landing/remotion/scenes/laptop";
import {
  InboxComposition,
  KnowledgeComposition,
  HandoffComposition,
  BookingComposition,
  InsightsComposition,
  TicketsComposition,
  ConversationComposition,
  BrandComposition,
  PresenceComposition,
} from "../modules/landing/remotion/product-demos";

export function HeroRemotionRoot() {
  return (
    <>
      <Composition
        id="Mot-Agenci"
        component={InboxComposition}
        width={960}
        height={580}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Din-kunnskap"
        component={KnowledgeComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Menneskelig-hjelp"
        component={HandoffComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Enkel-booking"
        component={BookingComposition}
        width={600}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Samtaleinnsikt"
        component={InsightsComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Automatisk-stotte"
        component={TicketsComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="AI-samtale"
        component={ConversationComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Din-stemme"
        component={BrandComposition}
        width={720}
        height={400}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Pa-nettsiden"
        component={PresenceComposition}
        width={400}
        height={360}
        fps={30}
        durationInFrames={330}
      />
      <Composition
        id="Pa-farten"
        component={CityConversation}
        width={368}
        height={304}
        fps={30}
        durationInFrames={418}
      />
      <Composition
        id="Pa-telefonen"
        component={CallConversation}
        width={368}
        height={304}
        fps={30}
        durationInFrames={496}
      />
      <Composition
        id="Hjemme"
        component={LaptopConversation}
        width={368}
        height={304}
        fps={30}
        durationInFrames={317}
      />
    </>
  );
}
